-- 코드를 입력하세요
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    sum(o.AMOUNT * p.PRICE) as TOTAL_SALES
FROM FOOD_PRODUCT p
INNER JOIN FOOD_ORDER o ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE o.PRODUCE_DATE like '2022-05%'
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID ASC
;